language: node_js
script: "yarn run travis"
node_js:
  - "6.9.1"
branches:
  only: master
cache: yarn
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
