language: node_js
before_install:
  - export PATH=$TRAVIS_BUILD_DIR/vendor:$PATH
install:
  - $TRAVIS_BUILD_DIR/vendor/yarn
script: "yarn run travis"
node_js:
  - "6.9.1"
branches:
  only: master
cache: yarn
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
