language: node_js
script: "npm run travis"
node_js:
  - "5.6.0"
branches:
  only: master
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
