language: node_js
node_js:
  - node

cache: yarn

before_install:
  - export PATH=$TRAVIS_BUILD_DIR/vendor:$PATH
  - npm config set @zendesk:registry https://zdrepo.jfrog.io/zdrepo/api/npm/npm/
  - npm config set //zdrepo.jfrog.io/zdrepo/api/npm/npm/:_password $ARTIFACTORY_PASSWORD
  - npm config set //zdrepo.jfrog.io/zdrepo/api/npm/npm/:username $ARTIFACTORY_USERNAME
  - npm config set //zdrepo.jfrog.io/zdrepo/api/npm/npm/:email $ARTIFACTORY_EMAIL
  - npm config set //zdrepo.jfrog.io/zdrepo/api/npm/npm/:always-auth true

install:
  - $TRAVIS_BUILD_DIR/vendor/yarn
  - npm config set _auth $ARTIFACTORY_API_KEY
  - npm config set email $ARTIFACTORY_EMAIL

before_deploy:
  - yarn styleguidist build

deploy:

  - provider: pages
    github_token: $GITHUB_TOKEN
    local_dir: styleguide
    skip_cleanup: true
    on:
      branch: master
      tags: true

  - provider: script
    script: npm publish
    skip_cleanup: true
    on:
      branch: master
      tags: true
