backend:
  name: github
  repo: zendeskgarden/website
  branch: agreen/initial-gatsby # Branch to update (optional; defaults to master)

media_folder: content/assets
public_folder: /img

collections:
  - label: "Content Strategy"
    name: "content-strategy"
    folder: "content/content-strategy"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
